"""empty message

Revision ID: 1154c256159c
Revises: ae33c88c28b7
Create Date: 2021-01-13 17:33:08.132500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1154c256159c'
down_revision = 'ae33c88c28b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
